
// debug um cogigo com todos os tipos de debugers

const num = 2;
try {
    let numero = num * multiplo;
    console.log(numero);
} catch (error) {
    console.log("ocorre um erro", error);
}

